version: "3"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    ports:
      - "8001:8000"
    depends_on:
      - db
      - google_drive_integration
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  google_drive_integration:
    build:
      context: ./google_drive_integration
    ports:
      - "8002:8001"